version: "3.9"

services:
  peradaban:
    image: ghcr.io/warung-international/peradaban:master
    env_file: .env
    volumes:
      - ./logs:/app/logs
    networks:
      - peradaban-network
    restart:
      on-failure
  utils:
    restart: on-failure
    image: ghcr.io/warung-international/utils:master
    env_file: .env

networks:
  peradaban-network:
