version: "3.9"

services:
  peradaban:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./logs:/app/logs
    networks:
      - peradaban-network
    restart:
      always

networks:
  peradaban-network:
