name: Build Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: warung-international/peradaban

jobs:
  lint:
    name: runner / Pre-commit actions (Production)
    runs-on: ubuntu-latest
    steps:
      - id: app_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v2
        with:
          token: ${{ steps.app_token.outputs.token }}
      - name: Set up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: "3.10.x"
      - name: Setup annotations
        uses: PennyDreadfulMTG/setup-linters@main
      - name: Install Dependencies
        run: |
          pip install pre-commit
      - name: Run Pre-commit
        continue-on-error: true
        run: |
          pre-commit run --all-files
      - name: Commit Fixes (if any)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "fix: pre-commit auto fixes"

  build_ghcr:
    name: runner / Build Docker Image actions
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Actions
        id: actions_checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
