name: precommit-action
on: [pull_request]
jobs:
  linter_name:
    name: runner / Pre-commit actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.10.x'
      - name: Setup annotations
        uses: PennyDreadfulMTG/setup-linters@main
      - name: Install Pre-commit
        run: |
          pip install pre-commit
      - name: Run Pre-commit
        run: |
          pre-commit run --all-files
