name: precommit-action
on: [push, pull_request]
jobs:
  linter_name:
    name: runner / Pre-commit actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.10.x'
      - name: Setup annotations
        uses: PennyDreadfulMTG/setup-linters@main
      - name: Install Pre-commit
        run: |
          pip install pre-commit
      - name: Run Pre-commit
        id: precommit
        continue-on-error: true
        run: |
          pre-commit run --all-files
      - name: Upload modified files (if any)
        if: steps.precommit.outcome == 'failure'
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git commit -m "chore: pre-commit fixes" . 
          git push origin master